// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public final class DataVisualizerImpl {
  private DataVisualizerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_LocationFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024datavisualizer.proto\022\016datavisualizer\"." +
      "\n\032PollutionStatisticsRequest\022\020\n\010location" +
      "\030\001 \001(\t\"S\n\023PollutionStatistics\022\035\n\025average" +
      "PollutionLevel\030\001 \001(\002\022\035\n\025highestPollution" +
      "Level\030\002 \001(\002\")\n\025LocationFilterRequest\022\020\n\010" +
      "location\030\001 \001(\t\"+\n\027FavoriteLocationReques" +
      "t\022\020\n\010location\030\001 \001(\t\"*\n\030FavoriteLocationR" +
      "esponse\022\016\n\006status\030\001 \001(\t\"d\n\016PollutionLeve" +
      "l\022\020\n\010location\030\001 \001(\t\022\025\n\rpollutionType\030\002 \001" +
      "(\t\022\026\n\016pollutionLevel\030\003 \001(\002\022\021\n\ttimestamp\030" +
      "\004 \001(\0032\327\002\n\021DataVisualization\022m\n\026GetPollut" +
      "ionStatistics\022*.datavisualizer.Pollution" +
      "StatisticsRequest\032#.datavisualizer.Pollu" +
      "tionStatistics\"\0000\001\022c\n\024FilterDataByLocati" +
      "on\022%.datavisualizer.LocationFilterReques" +
      "t\032\036.datavisualizer.PollutionLevel\"\000(\0010\001\022" +
      "n\n\023SetFavoriteLocation\022\'.datavisualizer." +
      "FavoriteLocationRequest\032(.datavisualizer" +
      ".FavoriteLocationResponse\"\000(\0010\001B)\n\021ds.da" +
      "tavisualizerB\022DataVisualizerImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatisticsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_PollutionStatistics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatistics_descriptor,
        new java.lang.String[] { "AveragePollutionLevel", "HighestPollutionLevel", });
    internal_static_datavisualizer_LocationFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_LocationFilterRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_datavisualizer_PollutionLevel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datavisualizer_PollutionLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionLevel_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
