// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public final class DataVisualizerImpl {
  private DataVisualizerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_LocationFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024datavisualizer.proto\022\016datavisualizer\"." +
      "\n\032PollutionStatisticsRequest\022\020\n\010location" +
      "\030\001 \001(\t\"4\n\023PollutionStatistics\022\035\n\025average" +
      "PollutionLevel\030\001 \001(\002\")\n\025LocationFilterRe" +
      "quest\022\020\n\010location\030\001 \001(\t\"+\n\027FavoriteLocat" +
      "ionRequest\022\020\n\010location\030\001 \001(\t\"*\n\030Favorite" +
      "LocationResponse\022\016\n\006status\030\001 \001(\t\"d\n\016Poll" +
      "utionLevel\022\020\n\010location\030\001 \001(\t\022\025\n\rpollutio" +
      "nType\030\002 \001(\t\022\026\n\016pollutionLevel\030\003 \001(\002\022\021\n\tt" +
      "imestamp\030\004 \001(\0032\327\002\n\021DataVisualization\022m\n\026" +
      "GetPollutionStatistics\022*.datavisualizer." +
      "PollutionStatisticsRequest\032#.datavisuali" +
      "zer.PollutionStatistics\"\0000\001\022c\n\024FilterDat" +
      "aByLocation\022%.datavisualizer.LocationFil" +
      "terRequest\032\036.datavisualizer.PollutionLev" +
      "el\"\000(\0010\001\022n\n\023SetFavoriteLocation\022\'.datavi" +
      "sualizer.FavoriteLocationRequest\032(.datav" +
      "isualizer.FavoriteLocationResponse\"\000(\0010\001" +
      "B)\n\021ds.datavisualizerB\022DataVisualizerImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatisticsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_PollutionStatistics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatistics_descriptor,
        new java.lang.String[] { "AveragePollutionLevel", });
    internal_static_datavisualizer_LocationFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_LocationFilterRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_datavisualizer_PollutionLevel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datavisualizer_PollutionLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionLevel_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
