// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public final class DataVisualizerImpl {
  private DataVisualizerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionStatistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_LocationFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datavisualizer_PollutionLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datavisualizer_PollutionLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024datavisualizer.proto\022\016datavisualizer\"." +
      "\n\032PollutionStatisticsRequest\022\020\n\010location" +
      "\030\001 \001(\t\"<\n\023PollutionStatistics\022\026\n\016statist" +
      "ic_type\030\001 \001(\t\022\r\n\005value\030\002 \001(\002\")\n\025Location" +
      "FilterRequest\022\020\n\010location\030\001 \001(\t\"+\n\027Favor" +
      "iteLocationRequest\022\020\n\010location\030\001 \001(\t\"+\n\030" +
      "FavoriteLocationResponse\022\017\n\007message\030\001 \001(" +
      "\t\"-\n\016PollutionLevel\022\r\n\005value\030\001 \001(\002\022\014\n\004un" +
      "it\030\002 \001(\t2\327\002\n\021DataVisualization\022m\n\026GetPol" +
      "lutionStatistics\022*.datavisualizer.Pollut" +
      "ionStatisticsRequest\032#.datavisualizer.Po" +
      "llutionStatistics\"\0000\001\022c\n\024FilterDataByLoc" +
      "ation\022%.datavisualizer.LocationFilterReq" +
      "uest\032\036.datavisualizer.PollutionLevel\"\000(\001" +
      "0\001\022n\n\023SetFavoriteLocation\022\'.datavisualiz" +
      "er.FavoriteLocationRequest\032(.datavisuali" +
      "zer.FavoriteLocationResponse\"\000(\0010\001B)\n\021ds" +
      ".datavisualizerB\022DataVisualizerImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datavisualizer_PollutionStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datavisualizer_PollutionStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatisticsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_PollutionStatistics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datavisualizer_PollutionStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionStatistics_descriptor,
        new java.lang.String[] { "StatisticType", "Value", });
    internal_static_datavisualizer_LocationFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datavisualizer_LocationFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_LocationFilterRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datavisualizer_FavoriteLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_datavisualizer_FavoriteLocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datavisualizer_FavoriteLocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_FavoriteLocationResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_datavisualizer_PollutionLevel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datavisualizer_PollutionLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datavisualizer_PollutionLevel_descriptor,
        new java.lang.String[] { "Value", "Unit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
