// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public interface FavoriteLocationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datavisualizer.FavoriteLocationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
