// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public interface PollutionStatisticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datavisualizer.PollutionStatisticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
