// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public interface PollutionStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datavisualizer.PollutionStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float averagePollutionLevel = 1;</code>
   */
  float getAveragePollutionLevel();
}
