// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public interface PollutionLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datavisualizer.PollutionLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string pollutionType = 2;</code>
   */
  java.lang.String getPollutionType();
  /**
   * <code>string pollutionType = 2;</code>
   */
  com.google.protobuf.ByteString
      getPollutionTypeBytes();

  /**
   * <code>float pollutionLevel = 3;</code>
   */
  float getPollutionLevel();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
