// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datavisualizer.proto

package ds.datavisualizer;

public interface PollutionLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datavisualizer.PollutionLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   */
  float getValue();

  /**
   * <code>string unit = 2;</code>
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 2;</code>
   */
  com.google.protobuf.ByteString
      getUnitBytes();
}
