// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface AirPollutionAlertsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.AirPollutionAlertsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 threshold = 1;</code>
   */
  int getThreshold();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
