// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface AirPollutionAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.AirPollutionAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  java.util.List<grpc.distributedca.AirPollutionAlert> 
      getAlertsList();
  /**
   * <code>repeated .smartpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  grpc.distributedca.AirPollutionAlert getAlerts(int index);
  /**
   * <code>repeated .smartpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .smartpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  java.util.List<? extends grpc.distributedca.AirPollutionAlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .smartpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  grpc.distributedca.AirPollutionAlertOrBuilder getAlertsOrBuilder(
      int index);
}
