// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface LocationFilterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.LocationFilterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
