// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface PollutionStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.PollutionStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statistic_type = 1;</code>
   */
  java.lang.String getStatisticType();
  /**
   * <code>string statistic_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatisticTypeBytes();

  /**
   * <code>float value = 2;</code>
   */
  float getValue();
}
