// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface WaterPollutionAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.WaterPollutionAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  java.util.List<grpc.distributedca.WaterPollutionAlert> 
      getAlertsList();
  /**
   * <code>repeated .smartpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  grpc.distributedca.WaterPollutionAlert getAlerts(int index);
  /**
   * <code>repeated .smartpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .smartpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  java.util.List<? extends grpc.distributedca.WaterPollutionAlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .smartpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  grpc.distributedca.WaterPollutionAlertOrBuilder getAlertsOrBuilder(
      int index);
}
