// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutiontracking.proto

package grpc.distributedca;

public interface WaterPollutionHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartpollutiontracker.WaterPollutionHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_time = 1;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 2;</code>
   */
  long getEndTime();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
