// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airpollutiontracker.proto

package ds.airpollutiontracker;

public final class AirPollutionTrackerImpl {
  private AirPollutionTrackerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionAlertsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionAlert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpollutiontracker_AirPollutionLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpollutiontracker_AirPollutionLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031airpollutiontracker.proto\022\023airpollutio" +
      "ntracker\"T\n\032AirPollutionHistoryRequest\022\022" +
      "\n\nstart_time\030\001 \001(\003\022\020\n\010end_time\030\002 \001(\003\022\020\n\010" +
      "location\030\003 \001(\t\"@\n\031AirPollutionAlertsRequ" +
      "est\022\021\n\tthreshold\030\001 \001(\005\022\020\n\010location\030\002 \001(\t" +
      "\"T\n\032AirPollutionAlertsResponse\0226\n\006alerts" +
      "\030\001 \003(\0132&.airpollutiontracker.AirPollutio" +
      "nAlert\"i\n\021AirPollutionAlert\022\020\n\010location\030" +
      "\001 \001(\t\022\026\n\016pollution_type\030\002 \001(\t\022\027\n\017polluti" +
      "on_level\030\003 \001(\002\022\021\n\ttimestamp\030\004 \001(\t\".\n\032Air" +
      "PollutionMonitorRequest\022\020\n\010location\030\001 \001(" +
      "\t\"i\n\021AirPollutionLevel\022\020\n\010location\030\001 \001(\t" +
      "\022\026\n\016pollution_type\030\002 \001(\t\022\027\n\017pollution_le" +
      "vel\030\003 \001(\002\022\021\n\ttimestamp\030\004 \001(\t2\376\002\n\023AirPoll" +
      "utionTracker\022u\n\026GetAirPollutionHistory\022/" +
      ".airpollutiontracker.AirPollutionHistory" +
      "Request\032&.airpollutiontracker.AirPolluti" +
      "onLevel\"\0000\001\022z\n\025GetAirPollutionAlerts\022..a" +
      "irpollutiontracker.AirPollutionAlertsReq" +
      "uest\032/.airpollutiontracker.AirPollutionA" +
      "lertsResponse\"\000\022t\n\023MonitorAirPollution\022/" +
      ".airpollutiontracker.AirPollutionMonitor" +
      "Request\032&.airpollutiontracker.AirPolluti" +
      "onLevel\"\000(\0010\001B3\n\026ds.airpollutiontrackerB" +
      "\027AirPollutionTrackerImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airpollutiontracker_AirPollutionHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airpollutiontracker_AirPollutionHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionHistoryRequest_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "Location", });
    internal_static_airpollutiontracker_AirPollutionAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airpollutiontracker_AirPollutionAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionAlertsRequest_descriptor,
        new java.lang.String[] { "Threshold", "Location", });
    internal_static_airpollutiontracker_AirPollutionAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airpollutiontracker_AirPollutionAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionAlertsResponse_descriptor,
        new java.lang.String[] { "Alerts", });
    internal_static_airpollutiontracker_AirPollutionAlert_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_airpollutiontracker_AirPollutionAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionAlert_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
    internal_static_airpollutiontracker_AirPollutionMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_airpollutiontracker_AirPollutionMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionMonitorRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_airpollutiontracker_AirPollutionLevel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_airpollutiontracker_AirPollutionLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpollutiontracker_AirPollutionLevel_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
