// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airpollutiontracker.proto

package ds.airpollutiontracker;

public interface AirPollutionAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollutiontracker.AirPollutionAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .airpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  java.util.List<ds.airpollutiontracker.AirPollutionAlert> 
      getAlertsList();
  /**
   * <code>repeated .airpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  ds.airpollutiontracker.AirPollutionAlert getAlerts(int index);
  /**
   * <code>repeated .airpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .airpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  java.util.List<? extends ds.airpollutiontracker.AirPollutionAlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .airpollutiontracker.AirPollutionAlert alerts = 1;</code>
   */
  ds.airpollutiontracker.AirPollutionAlertOrBuilder getAlertsOrBuilder(
      int index);
}
