// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airpollutiontracker.proto

package ds.airpollutiontracker;

public interface AirPollutionMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollutiontracker.AirPollutionMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
