// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterpollutiontracker.proto

package ds.waterpollutiontracker;

public interface WaterPollutionLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollutiontracker.WaterPollutionLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string pollution_type = 2;</code>
   */
  java.lang.String getPollutionType();
  /**
   * <code>string pollution_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getPollutionTypeBytes();

  /**
   * <code>float pollution_level = 3;</code>
   */
  float getPollutionLevel();

  /**
   * <code>string timestamp = 4;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
