// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterpollutiontracker.proto

package ds.waterpollutiontracker;

/**
 * Protobuf type {@code waterpollutiontracker.WaterPollutionAlertsResponse}
 */
public  final class WaterPollutionAlertsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:waterpollutiontracker.WaterPollutionAlertsResponse)
    WaterPollutionAlertsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterPollutionAlertsResponse.newBuilder() to construct.
  private WaterPollutionAlertsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterPollutionAlertsResponse() {
    alerts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WaterPollutionAlertsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              alerts_ = new java.util.ArrayList<ds.waterpollutiontracker.WaterPollutionAlert>();
              mutable_bitField0_ |= 0x00000001;
            }
            alerts_.add(
                input.readMessage(ds.waterpollutiontracker.WaterPollutionAlert.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        alerts_ = java.util.Collections.unmodifiableList(alerts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.waterpollutiontracker.WaterPollutionTrackerImpl.internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.waterpollutiontracker.WaterPollutionTrackerImpl.internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.waterpollutiontracker.WaterPollutionAlertsResponse.class, ds.waterpollutiontracker.WaterPollutionAlertsResponse.Builder.class);
  }

  public static final int ALERTS_FIELD_NUMBER = 1;
  private java.util.List<ds.waterpollutiontracker.WaterPollutionAlert> alerts_;
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  public java.util.List<ds.waterpollutiontracker.WaterPollutionAlert> getAlertsList() {
    return alerts_;
  }
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  public java.util.List<? extends ds.waterpollutiontracker.WaterPollutionAlertOrBuilder> 
      getAlertsOrBuilderList() {
    return alerts_;
  }
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  public int getAlertsCount() {
    return alerts_.size();
  }
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  public ds.waterpollutiontracker.WaterPollutionAlert getAlerts(int index) {
    return alerts_.get(index);
  }
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  public ds.waterpollutiontracker.WaterPollutionAlertOrBuilder getAlertsOrBuilder(
      int index) {
    return alerts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alerts_.size(); i++) {
      output.writeMessage(1, alerts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alerts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.waterpollutiontracker.WaterPollutionAlertsResponse)) {
      return super.equals(obj);
    }
    ds.waterpollutiontracker.WaterPollutionAlertsResponse other = (ds.waterpollutiontracker.WaterPollutionAlertsResponse) obj;

    boolean result = true;
    result = result && getAlertsList()
        .equals(other.getAlertsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlertsCount() > 0) {
      hash = (37 * hash) + ALERTS_FIELD_NUMBER;
      hash = (53 * hash) + getAlertsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.waterpollutiontracker.WaterPollutionAlertsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code waterpollutiontracker.WaterPollutionAlertsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:waterpollutiontracker.WaterPollutionAlertsResponse)
      ds.waterpollutiontracker.WaterPollutionAlertsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.waterpollutiontracker.WaterPollutionTrackerImpl.internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.waterpollutiontracker.WaterPollutionTrackerImpl.internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.waterpollutiontracker.WaterPollutionAlertsResponse.class, ds.waterpollutiontracker.WaterPollutionAlertsResponse.Builder.class);
    }

    // Construct using ds.waterpollutiontracker.WaterPollutionAlertsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAlertsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        alertsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.waterpollutiontracker.WaterPollutionTrackerImpl.internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor;
    }

    @java.lang.Override
    public ds.waterpollutiontracker.WaterPollutionAlertsResponse getDefaultInstanceForType() {
      return ds.waterpollutiontracker.WaterPollutionAlertsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.waterpollutiontracker.WaterPollutionAlertsResponse build() {
      ds.waterpollutiontracker.WaterPollutionAlertsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.waterpollutiontracker.WaterPollutionAlertsResponse buildPartial() {
      ds.waterpollutiontracker.WaterPollutionAlertsResponse result = new ds.waterpollutiontracker.WaterPollutionAlertsResponse(this);
      int from_bitField0_ = bitField0_;
      if (alertsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          alerts_ = java.util.Collections.unmodifiableList(alerts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alerts_ = alerts_;
      } else {
        result.alerts_ = alertsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.waterpollutiontracker.WaterPollutionAlertsResponse) {
        return mergeFrom((ds.waterpollutiontracker.WaterPollutionAlertsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.waterpollutiontracker.WaterPollutionAlertsResponse other) {
      if (other == ds.waterpollutiontracker.WaterPollutionAlertsResponse.getDefaultInstance()) return this;
      if (alertsBuilder_ == null) {
        if (!other.alerts_.isEmpty()) {
          if (alerts_.isEmpty()) {
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlertsIsMutable();
            alerts_.addAll(other.alerts_);
          }
          onChanged();
        }
      } else {
        if (!other.alerts_.isEmpty()) {
          if (alertsBuilder_.isEmpty()) {
            alertsBuilder_.dispose();
            alertsBuilder_ = null;
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alertsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAlertsFieldBuilder() : null;
          } else {
            alertsBuilder_.addAllMessages(other.alerts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.waterpollutiontracker.WaterPollutionAlertsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.waterpollutiontracker.WaterPollutionAlertsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ds.waterpollutiontracker.WaterPollutionAlert> alerts_ =
      java.util.Collections.emptyList();
    private void ensureAlertsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        alerts_ = new java.util.ArrayList<ds.waterpollutiontracker.WaterPollutionAlert>(alerts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.waterpollutiontracker.WaterPollutionAlert, ds.waterpollutiontracker.WaterPollutionAlert.Builder, ds.waterpollutiontracker.WaterPollutionAlertOrBuilder> alertsBuilder_;

    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public java.util.List<ds.waterpollutiontracker.WaterPollutionAlert> getAlertsList() {
      if (alertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alerts_);
      } else {
        return alertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public int getAlertsCount() {
      if (alertsBuilder_ == null) {
        return alerts_.size();
      } else {
        return alertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public ds.waterpollutiontracker.WaterPollutionAlert getAlerts(int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);
      } else {
        return alertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder setAlerts(
        int index, ds.waterpollutiontracker.WaterPollutionAlert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.set(index, value);
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder setAlerts(
        int index, ds.waterpollutiontracker.WaterPollutionAlert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder addAlerts(ds.waterpollutiontracker.WaterPollutionAlert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder addAlerts(
        int index, ds.waterpollutiontracker.WaterPollutionAlert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(index, value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder addAlerts(
        ds.waterpollutiontracker.WaterPollutionAlert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder addAlerts(
        int index, ds.waterpollutiontracker.WaterPollutionAlert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder addAllAlerts(
        java.lang.Iterable<? extends ds.waterpollutiontracker.WaterPollutionAlert> values) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alerts_);
        onChanged();
      } else {
        alertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder clearAlerts() {
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public Builder removeAlerts(int index) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.remove(index);
        onChanged();
      } else {
        alertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public ds.waterpollutiontracker.WaterPollutionAlert.Builder getAlertsBuilder(
        int index) {
      return getAlertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public ds.waterpollutiontracker.WaterPollutionAlertOrBuilder getAlertsOrBuilder(
        int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);  } else {
        return alertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public java.util.List<? extends ds.waterpollutiontracker.WaterPollutionAlertOrBuilder> 
         getAlertsOrBuilderList() {
      if (alertsBuilder_ != null) {
        return alertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alerts_);
      }
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public ds.waterpollutiontracker.WaterPollutionAlert.Builder addAlertsBuilder() {
      return getAlertsFieldBuilder().addBuilder(
          ds.waterpollutiontracker.WaterPollutionAlert.getDefaultInstance());
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public ds.waterpollutiontracker.WaterPollutionAlert.Builder addAlertsBuilder(
        int index) {
      return getAlertsFieldBuilder().addBuilder(
          index, ds.waterpollutiontracker.WaterPollutionAlert.getDefaultInstance());
    }
    /**
     * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
     */
    public java.util.List<ds.waterpollutiontracker.WaterPollutionAlert.Builder> 
         getAlertsBuilderList() {
      return getAlertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.waterpollutiontracker.WaterPollutionAlert, ds.waterpollutiontracker.WaterPollutionAlert.Builder, ds.waterpollutiontracker.WaterPollutionAlertOrBuilder> 
        getAlertsFieldBuilder() {
      if (alertsBuilder_ == null) {
        alertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ds.waterpollutiontracker.WaterPollutionAlert, ds.waterpollutiontracker.WaterPollutionAlert.Builder, ds.waterpollutiontracker.WaterPollutionAlertOrBuilder>(
                alerts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        alerts_ = null;
      }
      return alertsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:waterpollutiontracker.WaterPollutionAlertsResponse)
  }

  // @@protoc_insertion_point(class_scope:waterpollutiontracker.WaterPollutionAlertsResponse)
  private static final ds.waterpollutiontracker.WaterPollutionAlertsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.waterpollutiontracker.WaterPollutionAlertsResponse();
  }

  public static ds.waterpollutiontracker.WaterPollutionAlertsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterPollutionAlertsResponse>
      PARSER = new com.google.protobuf.AbstractParser<WaterPollutionAlertsResponse>() {
    @java.lang.Override
    public WaterPollutionAlertsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WaterPollutionAlertsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WaterPollutionAlertsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterPollutionAlertsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.waterpollutiontracker.WaterPollutionAlertsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

