// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterpollutiontracker.proto

package ds.waterpollutiontracker;

public interface WaterPollutionAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollutiontracker.WaterPollutionAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  java.util.List<ds.waterpollutiontracker.WaterPollutionAlert> 
      getAlertsList();
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  ds.waterpollutiontracker.WaterPollutionAlert getAlerts(int index);
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  java.util.List<? extends ds.waterpollutiontracker.WaterPollutionAlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .waterpollutiontracker.WaterPollutionAlert alerts = 1;</code>
   */
  ds.waterpollutiontracker.WaterPollutionAlertOrBuilder getAlertsOrBuilder(
      int index);
}
