// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterpollutiontracker.proto

package ds.waterpollutiontracker;

public interface WaterPollutionMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollutiontracker.WaterPollutionMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
