// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterpollutiontracker.proto

package ds.waterpollutiontracker;

public final class WaterPollutionTrackerImpl {
  private WaterPollutionTrackerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionAlert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollutiontracker_WaterPollutionLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollutiontracker_WaterPollutionLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033waterpollutiontracker.proto\022\025waterpoll" +
      "utiontracker\"V\n\034WaterPollutionHistoryReq" +
      "uest\022\022\n\nstart_time\030\001 \001(\003\022\020\n\010end_time\030\002 \001" +
      "(\003\022\020\n\010location\030\003 \001(\t\"B\n\033WaterPollutionAl" +
      "ertsRequest\022\021\n\tthreshold\030\001 \001(\005\022\020\n\010locati" +
      "on\030\002 \001(\t\"Z\n\034WaterPollutionAlertsResponse" +
      "\022:\n\006alerts\030\001 \003(\0132*.waterpollutiontracker" +
      ".WaterPollutionAlert\"k\n\023WaterPollutionAl" +
      "ert\022\020\n\010location\030\001 \001(\t\022\026\n\016pollution_type\030" +
      "\002 \001(\t\022\027\n\017pollution_level\030\003 \001(\002\022\021\n\ttimest" +
      "amp\030\004 \001(\t\"0\n\034WaterPollutionMonitorReques" +
      "t\022\020\n\010location\030\001 \001(\t\"k\n\023WaterPollutionLev" +
      "el\022\020\n\010location\030\001 \001(\t\022\026\n\016pollution_type\030\002" +
      " \001(\t\022\027\n\017pollution_level\030\003 \001(\002\022\021\n\ttimesta" +
      "mp\030\004 \001(\t2\237\003\n\025WaterPollutionTracker\022\177\n\030Ge" +
      "tWaterPollutionHistory\0223.waterpollutiont" +
      "racker.WaterPollutionHistoryRequest\032*.wa" +
      "terpollutiontracker.WaterPollutionLevel\"" +
      "\0000\001\022\204\001\n\027GetWaterPollutionAlerts\0222.waterp" +
      "ollutiontracker.WaterPollutionAlertsRequ" +
      "est\0323.waterpollutiontracker.WaterPolluti" +
      "onAlertsResponse\"\000\022~\n\025MonitorWaterPollut" +
      "ion\0223.waterpollutiontracker.WaterPolluti" +
      "onMonitorRequest\032*.waterpollutiontracker" +
      ".WaterPollutionLevel\"\000(\0010\001B7\n\030ds.waterpo" +
      "llutiontrackerB\031WaterPollutionTrackerImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterpollutiontracker_WaterPollutionHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterpollutiontracker_WaterPollutionHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionHistoryRequest_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "Location", });
    internal_static_waterpollutiontracker_WaterPollutionAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterpollutiontracker_WaterPollutionAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionAlertsRequest_descriptor,
        new java.lang.String[] { "Threshold", "Location", });
    internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionAlertsResponse_descriptor,
        new java.lang.String[] { "Alerts", });
    internal_static_waterpollutiontracker_WaterPollutionAlert_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterpollutiontracker_WaterPollutionAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionAlert_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
    internal_static_waterpollutiontracker_WaterPollutionMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterpollutiontracker_WaterPollutionMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionMonitorRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_waterpollutiontracker_WaterPollutionLevel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_waterpollutiontracker_WaterPollutionLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollutiontracker_WaterPollutionLevel_descriptor,
        new java.lang.String[] { "Location", "PollutionType", "PollutionLevel", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
